import type {RuntimeEvent} from './types.js';
import type {SubmitRequest} from './types.js';
import type {AgentRuntime} from './types.js';

const wait = (duration: number, signal: AbortSignal): Promise<void> =>
	new Promise((resolve, reject) => {
		const finish = () => {
			signal.removeEventListener('abort', abort);
			resolve();
		};
		const timer = setTimeout(finish, duration);
		const abort = () => {
			clearTimeout(timer);
			signal.removeEventListener('abort', abort);
			reject(signal.reason instanceof Error ? signal.reason : new Error('Aborted'));
		};
		if (signal.aborted) abort();
		else signal.addEventListener('abort', abort, {once: true});
	});

export class MockRuntime implements AgentRuntime {
	readonly #responseDelay: number;
	#disposed = false;

	constructor(responseDelay = 700) {
		this.#responseDelay = responseDelay;
	}

	async *run(request: SubmitRequest, signal: AbortSignal): AsyncIterable<RuntimeEvent> {
		if (this.#disposed) throw new Error('Runtime has been disposed');
		yield {type: 'turn.started', request};

		if (request.mode === 'bash') {
			yield {
				type: 'message.appended',
				message: {
					id: `bash-${request.id}`,
					kind: 'tool',
					name: 'Bash',
					status: 'success',
					summary: 'UI-only command preview',
					detail: 'No command was executed.',
					group: 'bash',
				},
			};
			yield {type: 'turn.completed', turnId: request.id};
			return;
		}

		yield {type: 'status.changed', status: 'thinking'};
		await wait(this.#responseDelay, signal);
		yield {
			type: 'message.appended',
			message: {
				id: `assistant-${request.id}`,
				kind: 'assistant',
				variant: 'text',
				content:
					'This response was generated by the local UI demo. No model, agent, tool, network, or filesystem operation ran.',
			},
		};
		yield {type: 'turn.completed', turnId: request.id};
	}

	dispose(): void {
		this.#disposed = true;
	}
}
